# Generated by Django 3.2.2 on 2021-05-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('Advisorid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photourl', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifyon', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('AssignUser', models.CharField(choices=[('0', 'Yes'), ('1', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Userid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifyon', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('AssignAdvisor', models.CharField(choices=[('0', 'Yes'), ('1', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifyon', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('Advisorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.advisor')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.user')),
            ],
        ),
    ]
