# Generated by Django 3.2.2 on 2021-05-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='modifyon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modifyon',
        ),
    ]
