# Generated by Django 3.2.2 on 2021-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0002_auto_20210509_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photourl',
            field=models.ImageField(upload_to='image'),
        ),
    ]
