# Generated by Django 3.2.2 on 2021-05-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0003_alter_advisor_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='photourl',
        ),
    ]
