# Generated by Django 3.2.2 on 2021-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0005_alter_booking_bookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
